version: '3.3'
services:
  santa-wishlist-front:
    image: santa-wishlist-front:latest
    environment:
      PORT: 3000
    ports:
      - 3000:3000
  santa-wishlist-back:
    image: santa-wishlist-back:latest
    environment:
      PORT: 5000
    ports:
      - 5000:5000